spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: LIZHONGJIE199608
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        #最大活跃连接数
        max-active: 8
        #最大空闲连接数
        max-idle: 8
        #最小空间连接数
        min-idle: 0

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 9999
  tomcat:
    uri-encoding: utf-8

